services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: pulseboard
      POSTGRES_USER: pulseboard_user
      POSTGRES_PASSWORD: ${PULSEBOARD_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pulseboard_postgres_data:/var/lib/postgresql/data

volumes:
  pulseboard_postgres_data: